spring:
  application:
    name: spring-cqrs
  datasource:
    url: jdbc:postgresql://localhost:5434/e-commerce-cqrs  #postgrede bu db'nin var olması gerek
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
