spring:
  application:
    name: spring-starter
  datasource:
    url: jdbc:postgresql://localhost:5434/library_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate: #
      ddl-auto: update
    show-sql: true